### ISSUE TITLE
Windows scheduled task action args is a blank string

### ISSUE THREAD

**Issue by mijdavis2** [chef-cookbooks/chef-client#681]
## Specs:
- chef-client cookbook:  v11.5.0
- chef-client: 15.10
- Windows server: 2019

## Expected:
`chef-client` cookbook creates a working scheduled task on windows servers.

## Actual:
The "Action" on the created scheduled task is as follows:
```
C:\Windows\system32\cmd.exe /c ""
```

Here's the attributes on the node where this is a problem:
```
config
    chef_server_url: https://chef-server.internal.***.com/organizations/***
    validation_client_name: ***-validator
    node_name: dev-test
    verify_api_cert: true
    start_handlers: 
    report_handlers: 
    exception_handlers: 

chef_license: accept
log_file: client.log
interval: 300
splay: 100
conf_dir: C:/chef
bin: C:/opscode/chef/bin/chef-client
log_dir: C:/chef/log
log_perm: 640
```

As you can see, the chef-client binary, the log dir, and the ruby binary are not present in the task action as they should be according to the docs. 

The Action should be something like:
```
cmd /c "C:\opscode\chef\embedded\bin\ruby.exe C:\opscode\chef\bin\chef-client -L C:\chef\chef-client.log -c C:\chef\client.rb"
```
